nav:
  - 语言学习:
    - 俄语:
      - 俄语语法: /Russian/Grammar for Russian.html
    - 物理: 
      - 预科物理: /Physics/语言学习/预科物理.Grammar.html
    - 化学:
      - 预科化学: /Chemistry/语言学习/预科化学.Grammar.html
    - 数学:
      - 预科数学: /Math/语言学习/预科数学.Grammar.html
  - 预科课程: 
    - 目录: /List/预科课程.html
    - 物理:
      - 预科物理课件: /Physics/预科物理课件.html
      - 预科物理教材: /Physics/预科物理教材.html
      - 热力学公式总结: /Physics/热力学公式总结.html
    - 化学:
      - 普通化学: /Chemistry/普通化学.html
    - 数学:
      - 预科数学: /Math/预科数学.html
      - 高中数学: /Math/高中数学.html
    - 信息:
      - 预科信息: /Information/预科信息.html
    - 历史:
      - 关于俄罗斯与俄罗斯人: /History/关于俄罗斯与俄罗斯人.html
      - 在俄罗斯学习与生活: /History/在俄罗斯学习与生活.html
    - 工程制图:
      - 工程制图: /Engineering%20graphics/工程制图.html
  - 软件工程:
    - 目录: /List/软件工程.html
    - Java: /Java/Java教材.html
  - 友链: /friends.html
  - 单词表: /Word.html




site_name: Russian Natural Science Wiki
site_url: https://itmo.ranying.xyz
site_description: 这个 Wiki 是我们整理的关于在俄罗斯留学时理工科学习的知识汇总，这个网站欢迎大家来贡献和修改内容。
site_author: ICSG-Group
repo_url: https://github.com/ITMO-Computer-Science-Group/Natural-Sciences-Wiki/
repo_name: GitHub
edit_uri: edit/main/
use_directory_urls: false
theme:
  name: material
  navigation_depth: 6
  language: zh
  logo: /theme/icon.png
  favicon: /theme/favicon.ico
  features:
    #- toc.integrate
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.indexes
    #- navigation.expand
    - navigation.sections
    - navigation.top
    - header.autohide
  palette:
    primary: deep purple

extra_javascript:
  - /mathjax/LaTeX.js

plugins:
  - search:
      lang:
        - en
        - ru
        - ja